[project]
name = 'Decentralized-Organ-Donation-and-Transplant-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donor-registration]
path = 'contracts/donor-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.matching-algorithm]
path = 'contracts/matching-algorithm.clar'
clarity_version = 2
epoch = 2.5

[contracts.recipient-listing]
path = 'contracts/recipient-listing.clar'
clarity_version = 2
epoch = 2.5

[contracts.transport-logistics]
path = 'contracts/transport-logistics.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
